on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test homework
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Homework Checker
        id: homeworkchecker
        uses: jandoornbos/oop-homework-checker-action@main